######################################################################
# Automatically generated by qmake (2.01a) ?? 2? 23 18:25:46 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h scribblearea.h \
    common.h
SOURCES += main.cpp mainwindow.cpp scribblearea.cpp
RESOURCES += scribble.qrc 
FORMS += mainwindow.ui
